<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX4IaBlf\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX4IaBlf/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX4IaBlf.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX4IaBlf\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerX4IaBlf\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'X4IaBlf',
    'container.build_id' => 'ec752a9b',
    'container.build_time' => 1597415982,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX4IaBlf');
