<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEE0xLTV\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEE0xLTV/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEE0xLTV.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEE0xLTV\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEE0xLTV\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'EE0xLTV',
    'container.build_id' => '7a8d3079',
    'container.build_time' => 1597502926,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEE0xLTV');
