<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSpmecVh\srcApp_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSpmecVh/srcApp_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerSpmecVh.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevContainer::class, false)) {
    \class_alias(\ContainerSpmecVh\srcApp_KernelDevContainer::class, srcApp_KernelDevContainer::class, false);
}

return new \ContainerSpmecVh\srcApp_KernelDevContainer([
    'container.build_hash' => 'SpmecVh',
    'container.build_id' => '54d297c2',
    'container.build_time' => 1597416178,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSpmecVh');
